/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package heuristica;

import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Carlos
 */
public class Tela extends javax.swing.JFrame {

    private No[][] matriz; 
    private int linh;
    private int tamanhNo;
    private int colun;
    private int tipo;
    private Coordenada partida;
    private Coordenada chegada;
    private ArrayList<Coordenada> aberto;
    private ArrayList<Coordenada> caminho;    
    private ArrayList<Coordenada> caminhoGuloso;
    private boolean resolvido;

    /**
     * Creates new form TelaAEstrela
     */
    public Tela() {
        tamanhNo = 5;
        aberto = new ArrayList<>();
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpDesenho = new Desenho();
        btnPartida = new javax.swing.JButton();
        btnChegada = new javax.swing.JButton();
        btnMata = new javax.swing.JButton();
        btnBuraco = new javax.swing.JButton();
        btnPantano = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfLinh = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfColun = new javax.swing.JTextField();
        btnGerarMatriz = new javax.swing.JButton();
        btnResolv = new javax.swing.JButton();
        btnLimpo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        labelCustoA = new javax.swing.JLabel();
        btnAleatorio = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        labelCustoGulosa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jpDesenho.setBackground(new java.awt.Color(255, 255, 255));
        jpDesenho.setForeground(new java.awt.Color(255, 255, 255));
        jpDesenho.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jpDesenho.setMaximumSize(new java.awt.Dimension(300, 300));
        jpDesenho.setPreferredSize(new java.awt.Dimension(300, 300));
        jpDesenho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpDesenhoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpDesenhoLayout = new javax.swing.GroupLayout(jpDesenho);
        jpDesenho.setLayout(jpDesenhoLayout);
        jpDesenhoLayout.setHorizontalGroup(
            jpDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jpDesenhoLayout.setVerticalGroup(
            jpDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        btnPartida.setText("Partida");
        btnPartida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPartidaMouseClicked(evt);
            }
        });

        btnChegada.setText("Chegada");
        btnChegada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChegadaMouseClicked(evt);
            }
        });

        btnMata.setText("Mata");
        btnMata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMataMouseClicked(evt);
            }
        });

        btnBuraco.setText("Buraco");
        btnBuraco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuracoMouseClicked(evt);
            }
        });

        btnPantano.setText("Pantano");
        btnPantano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPantanoMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Busca Heurística");

        jLabel2.setText("Tamanho Matriz   Linh.:");

        jLabel3.setText("Colun.:");

        btnGerarMatriz.setText("Gerar");
        btnGerarMatriz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGerarMatrizMouseClicked(evt);
            }
        });

        btnResolv.setText("Resolver");
        btnResolv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResolvMouseClicked(evt);
            }
        });

        btnLimpo.setText("Limpo");
        btnLimpo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpoMouseClicked(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Instruções"));

        jLabel4.setText("Custos do caminho:");

        jLabel5.setText("Limpo: 1");

        jLabel6.setText("Mata: 2");

        jLabel7.setText("Pantano: 3");

        jLabel8.setText("Verticall = 10 x tipo");

        jLabel9.setText("Horizontall = 10 x tipo");

        jLabel10.setText("Diagonal = 14 x tipo");

        jLabel11.setText("Tipos Caminho:");

        jLabel12.setText("Sem Passagem:");

        jLabel13.setText("Buraco");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(0, 255, 51));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        jLabel14.setText("Chegada");

        jLabel15.setText("Partida");

        jLabel16.setText("Busca A*");

        jPanel7.setBackground(new java.awt.Color(255, 0, 51));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        jPanel14.setBackground(new java.awt.Color(0, 51, 204));
        jPanel14.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        jPanel15.setBackground(new java.awt.Color(255, 204, 51));
        jPanel15.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        jLabel17.setText("Busca Gulosa");

        jPanel16.setBackground(new java.awt.Color(255, 102, 255));
        jPanel16.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        jLabel18.setText("f(n) = g(n) + h(n)");

        jLabel19.setText("f(n) = h(n)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14))
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel18)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel13))))
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15))
                            .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16))
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13))
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel20.setText("Custo A*:");

        btnAleatorio.setText("Aleatório");
        btnAleatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAleatorioMouseClicked(evt);
            }
        });

        jLabel21.setText("Custo Gulosa:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnMata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPantano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnChegada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPartida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuraco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnResolv)
                    .addComponent(labelCustoA, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAleatorio)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelCustoGulosa, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jpDesenho, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jtfLinh, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jtfColun, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGerarMatriz)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfLinh, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jtfColun, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGerarMatriz))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnPartida)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnChegada)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnLimpo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnMata)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnPantano)
                            .addGap(9, 9, 9)
                            .addComponent(btnBuraco)
                            .addGap(32, 32, 32)
                            .addComponent(btnAleatorio)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(labelCustoGulosa, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel20)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(labelCustoA, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(13, 13, 13)
                            .addComponent(btnResolv))
                        .addComponent(jpDesenho, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarMatrizMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGerarMatrizMouseClicked
        gerar();
    }//GEN-LAST:event_btnGerarMatrizMouseClicked

    private boolean gerar() {
        if (jtfLinh.getText().trim().length() == 0 | jtfColun.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos");
            return false;
        }

        try {
            colun = Integer.parseInt(jtfColun.getText().trim());
            linh = Integer.parseInt(jtfLinh.getText().trim());

        } catch (Exception er) {
            JOptionPane.showMessageDialog(this, "Insira somente números inteiros!");
            return false;
        }
        if (colun <= 0 || linh <= 0 || colun > 200 || linh > 200) {
            JOptionPane.showMessageDialog(this, "Insira somente números inteiros maiores que zero e monores ou iguais a 200!");
            return false;
        }
        resolvido = false;
        if (colun > linh) {
            tamanhNo = 400 / colun;
        } else {
            tamanhNo = 400 / linh;
        }
        matriz = new No[colun][linh];
        for (int i = 0; i < colun; i++) {
            for (int j = 0; j < linh; j++) {
                matriz[i][j] = (new No(0));
                matriz[i][j].setCoordenada(new Coordenada(i, j));
            }
        }
        chegada = null;
        partida = null;
        caminho = null;
        caminhoGuloso = null;
        labelCustoA.setText("");
        labelCustoGulosa.setText("");
        jpDesenho.update(jpDesenho.getGraphics());

        return true;
    }


    private void btnPartidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPartidaMouseClicked
        tipo = 4;
    }//GEN-LAST:event_btnPartidaMouseClicked

    private void btnChegadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChegadaMouseClicked
        tipo = 5;
    }//GEN-LAST:event_btnChegadaMouseClicked

    private void btnBuracoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuracoMouseClicked
        tipo = 3;
    }//GEN-LAST:event_btnBuracoMouseClicked

    private void btnMataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMataMouseClicked
        tipo = 1;
    }//GEN-LAST:event_btnMataMouseClicked

    private void btnPantanoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPantanoMouseClicked
        tipo = 2;
    }//GEN-LAST:event_btnPantanoMouseClicked

    private void jpDesenhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpDesenhoMouseClicked
        if (matriz == null) {
            JOptionPane.showMessageDialog(this, "Insira a dimensão da matriz!");
            return;
        }
        if (resolvido) {
            return;
        }

        int x = evt.getX() / tamanhNo;
        int y = evt.getY() / tamanhNo;
        if (x >= colun || y >= linh) {
            return;
        }
        System.out.println(x);
        if (tipo == 4) {
            if (partida != null) {
                partida.setCoord(x, y);
            } else {
                partida = new Coordenada(x, y);
            }
        } else if (tipo == 5) {
            if (chegada != null) {
                chegada.setCoord(x, y);
            } else {
                chegada = new Coordenada(x, y);
            }
        } else {
            matriz[x][y].setTipo(tipo);

        }
        jpDesenho.update(jpDesenho.getGraphics());

    }//GEN-LAST:event_jpDesenhoMouseClicked

    private void btnResolvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResolvMouseClicked

        if (chegada == null | partida == null) {
            JOptionPane.showMessageDialog(this, "Sete a chegada e a saída!");
            return;
        }
        if (resolvido) {
            return;
        }
        criaGrafo();
        boolean g=gulosa();
        boolean a=aEstrela();
        if(a&&g);
        else if(!a&&!g)
            JOptionPane.showMessageDialog(this, "Não foi encontada nenhuma solução!");
        else if(!a)
            JOptionPane.showMessageDialog(this, "Não foi encontada nenhuma solução para Busca A*!");
        else
            JOptionPane.showMessageDialog(this, "Não foi encontada solução para Busca Gulosa!");
        jpDesenho.update(jpDesenho.getGraphics());
        
    }//GEN-LAST:event_btnResolvMouseClicked

    private void btnLimpoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpoMouseClicked
        tipo = 0;
    }//GEN-LAST:event_btnLimpoMouseClicked

    private void btnAleatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAleatorioMouseClicked
        if (!gerar()) {
            return;
        }

        Random r = new Random();
        int count = 0;
        int limit = (colun * linh) / 3;
        while (count < limit) {
            count++;
            matriz[r.nextInt(colun - 1)][r.nextInt(linh - 1)].setTipo(r.nextInt(3) + 1);
        }
        partida = new Coordenada(r.nextInt(colun - 1), r.nextInt(linh - 1));
        matriz[partida.getX()][partida.getY()].setTipo(0);
        chegada = new Coordenada(r.nextInt(colun - 1), r.nextInt(linh - 1));
        matriz[chegada.getX()][chegada.getY()].setTipo(0);

        jpDesenho.update(jpDesenho.getGraphics());
    }//GEN-LAST:event_btnAleatorioMouseClicked

    private boolean gulosa(){      
       caminhoGuloso=new ArrayList<>();
       if(chegada.getX()==partida.getX()&&chegada.getY()==partida.getY()){
           caminhoGuloso.add(partida);
           return true;
       }
       if(matriz[partida.getX()][partida.getY()].vizinhos().isEmpty()) return false;
       if(partida.caminhoGuloso(caminhoGuloso, chegada, matriz,(colun*linh))==null){
           caminhoGuloso=null;
           return false;
       }
       
       int custos=0;
       for(int i=(caminhoGuloso.size()-1);i>0;i--){
           if(caminhoGuloso.get(i).getX()==caminhoGuloso.get(i-1).getX()||caminhoGuloso.get(i).getY()==caminhoGuloso.get(i-1).getY()){
               custos=custos+(10*(noMatriz(caminhoGuloso.get(i-1)).getTipo()+1));
           }else{
               custos=custos+(14*(noMatriz(caminhoGuloso.get(i-1)).getTipo()+1));
           }
       }
       labelCustoGulosa.setText(String.valueOf(custos));
       return true;
    }
    
    private boolean aEstrela(){
        aberto = new ArrayList<>();
        No selecionado = matriz[partida.getX()][partida.getY()];
        selecionado.setG(0);
        selecionado.setFechado(true);
        custoVizinhos(selecionado);
        if (selecionado.getCoordenada().getX() == chegada.getX() && 
                selecionado.getCoordenada().getY() == chegada.getY()) {
            caminho = selecionado.retornaCaminho(new ArrayList<>());
            labelCustoA.setText(String.valueOf(selecionado.getG()));
            jpDesenho.update(jpDesenho.getGraphics());
            return false;
        }
        while (!aberto.isEmpty()) {
            selecionado = noMatriz(menorAberto());
            if (selecionado.getCoordenada().getX() == chegada.getX() && 
                    selecionado.getCoordenada().getY() == chegada.getY()) {
                caminho = selecionado.retornaCaminho(new ArrayList<>());
                labelCustoA.setText(String.valueOf(selecionado.getG()));
                resolvido = true;
                return true;
            }
            custoVizinhos(selecionado);
        }
        return false;
    }
    
    private Coordenada menorAberto() {

        Coordenada menor = aberto.get(0);
        int custo = noMatriz(menor).getF();
        for (Coordenada a : aberto) {
            if (noMatriz(a).getF() < custo) {
                custo = noMatriz(a).getF();
                menor = a;
            }
        }

        matriz[menor.getX()][menor.getY()].setFechado(true);
        aberto.remove(menor);
        return menor;
    }

    private No noMatriz(Coordenada c) {
        return matriz[c.getX()][c.getY()];
    }

    private void custoVizinhos(No pai) {
        ArrayList<Coordenada> vizinhos = pai.vizinhos();
        for (Coordenada n : vizinhos) {
            No vizin = noMatriz(n);
            if (!vizin.isFechado() && vizin.getTipo() != 3) {
                if (!aberto.contains(n)) {
                    aberto.add(n);
                }
                vizin.getF(pai);
                matriz[n.getX()][n.getY()] = vizin;
            }

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    private void criaGrafo() {
        for (int i = 0; i < colun; i++) {
            for (int j = 0; j < linh; j++) {
                No ins = matriz[i][j];
                if (ins.getTipo() != 3) {
                    ins.setH(chegada);
                    if (i > 0 && j > 0) {
                        if (matriz[i - 1][j - 1].getTipo() != 3) {
                            ins.addVizinho(new Coordenada(i - 1, j - 1));
                        }
                        if (matriz[i][j - 1].getTipo() != 3) {
                            ins.addVizinho(new Coordenada(i, j - 1));
                        }
                        if (matriz[i - 1][j].getTipo() != 3) {
                            ins.addVizinho(new Coordenada(i - 1, j));
                        }

                    } else if (i > 0) {
                        if (matriz[i - 1][j].getTipo() != 3) {
                            ins.addVizinho(new Coordenada(i - 1, j));
                        }
                    } else if (j > 0) {
                        if (matriz[i][j - 1].getTipo() != 3) {
                            ins.addVizinho(new Coordenada(i, j - 1));
                        }
                    }
                    if (i < colun - 1 && j > 0) {
                        if (matriz[i + 1][j - 1].getTipo() != 3) {
                            ins.addVizinho(new Coordenada(i + 1, j - 1));
                        }
                    }
                    if (j < linh - 1 && i > 0) {
                        if (matriz[i - 1][j + 1].getTipo() != 3) {
                            ins.addVizinho(new Coordenada(i - 1, j + 1));
                        }
                    }

                    if (i < colun - 1 && j < linh - 1) {
                        if (matriz[i + 1][j + 1].getTipo() != 3) {
                            ins.addVizinho(new Coordenada(i + 1, j + 1));
                        }
                        if (matriz[i][j + 1].getTipo() != 3) {
                            ins.addVizinho(new Coordenada(i, j + 1));
                        }
                        if (matriz[i + 1][j].getTipo() != 3) {
                            ins.addVizinho(new Coordenada(i + 1, j));
                        }
                    } else if (i < colun - 1) {
                        if (matriz[i + 1][j].getTipo() != 3) {
                            ins.addVizinho(new Coordenada(i + 1, j));
                        }
                    } else if (j < linh - 1) {
                        if (matriz[i][j + 1].getTipo() != 3) {
                            ins.addVizinho(new Coordenada(i, j + 1));
                        }
                    }
                    matriz[i][j] = ins;
                }
            }
        }
    }

    public class Desenho extends JPanel {

        @Override
        public void paintComponent(Graphics g) {
            super.paintComponent(g);
            this.setBackground(Color.DARK_GRAY);

            for (int i = 0; i < colun; i++) {
                for (int j = 0; j < linh; j++) {
                    int cor = matriz[i][j].getTipo();
                    switch (cor) {
                        case 0:
                            g.setColor(Color.white);
                            break;
                        case 1:
                            g.setColor(Color.GREEN);
                            break;
                        case 2:
                            g.setColor(Color.GRAY);
                            break;
                        case 3:
                            g.setColor(Color.BLACK);
                            break;
                        default:
                            break;

                    }
                    g.fillRect(i * tamanhNo, j * tamanhNo, tamanhNo, tamanhNo);
                    
                }
            }
            if (partida != null) {
                g.setColor(Color.BLUE);
                g.fillRect(partida.getX() * tamanhNo, partida.getY() * tamanhNo, tamanhNo, tamanhNo);
            }
            if (chegada != null) {
                g.setColor(Color.RED);
                g.fillRect(chegada.getX() * tamanhNo, chegada.getY() * tamanhNo, tamanhNo, tamanhNo);
            }
            if (caminho != null) {
                for (Coordenada n : caminho) {
                    g.setColor(Color.ORANGE);
                    g.fillOval(n.getX() * tamanhNo, n.getY() * tamanhNo, tamanhNo, tamanhNo);
                }
            }
            if (caminhoGuloso != null) {
                for (Coordenada n : caminhoGuloso) {
                    g.setColor(Color.PINK);
                    g.fillOval(n.getX() * tamanhNo, n.getY() * tamanhNo, tamanhNo, tamanhNo);
                }
            }
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAleatorio;
    private javax.swing.JButton btnBuraco;
    private javax.swing.JButton btnChegada;
    private javax.swing.JButton btnGerarMatriz;
    private javax.swing.JButton btnLimpo;
    private javax.swing.JButton btnMata;
    private javax.swing.JButton btnPantano;
    private javax.swing.JButton btnPartida;
    private javax.swing.JButton btnResolv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jpDesenho;
    private javax.swing.JTextField jtfColun;
    private javax.swing.JTextField jtfLinh;
    private javax.swing.JLabel labelCustoA;
    private javax.swing.JLabel labelCustoGulosa;
    // End of variables declaration//GEN-END:variables
}
